version: "3"
services:
    client:
     build: ./client
     ports:
         - "3000:3000"
    server:
     build: ./server
     links:
         - database
     ports: 
         - "8080:8080"
    database:
     image: mongo
     ports:
         - "27017:27017"
